website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy import func


class Movie(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    whoAdded = db.Column(db.String(150), db.ForeignKey('user.id'))
    dateAdded = db.Column(db.DateTime(timezone=True), default=func.now())
    haveWatched = db.Column(db.Boolean, default=False)


class Song(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    artist = db.Column(db.String(150))
    whoAdded = db.Column(db.String(150), db.ForeignKey('user.id'))
    dateAdded = db.Column(db.DateTime(timezone=True), default=func.now())
    haveListened = db.Column(db.Boolean, default=False)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    movieSuggestions = db.relationship('Movie')
    isAdmin = db.Column(db.Boolean, default=False)
    # sharedWith = db.Column(db.Integer, db.Foreignkey('user.id'))

website/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_jsglue import JSGlue

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    jsglue = JSGlue()

    app = Flask(__name__)
    jsglue.init_app(app)

    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL').replace("://", "ql://", 1)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Movie

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

website/auth.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from .models import User
from . import db
from werkzeug.security import check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Username does not exist, try again', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out successfully', category='success')
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user
from datetime import datetime
from .models import Movie, Song
from . import db
import random

views = Blueprint('views', __name__)

@views.route('/super/secret/epic/plan', methods=['POST', 'GET'])
@login_required
def superSecretEpicPlan():
    return render_template('epic.html', user=current_user)

@views.route('/', methods=['POST','GET'])
@login_required
def home():
    return render_template('home.html', user=current_user)


@views.route('/movies', methods=['POST', 'GET'])
@login_required
def movies():
    if request.method == 'POST':
        movie_name = request.form.get('movieNameInput')
        newMovie = Movie(name=movie_name, whoAdded=current_user.username, haveWatched=False)
        db.session.add(newMovie)
        db.session.commit()
        return redirect(url_for('views.movies'))
    allMovies = Movie.query.all()
    notWatched = []

    for movie in allMovies:
        if not movie.haveWatched:
            notWatched.append(movie)

    if len(notWatched) > 0:
        randMovie = random.choice(notWatched)
        return render_template("movies.html", user=current_user, movies=allMovies, randomMovie=randMovie.name)
    else:
        return render_template("movies.html", user=current_user, movies=allMovies, randomMovie="All Movies Watched")


@views.route('/movieDelete/<movie_id>')
@login_required
def movieDelete(movie_id):
    movie = Movie.query.filter_by(id=movie_id).first()
    if movie:
        msg_text = 'Successfully Deleted %s' % str(movie.name)
        db.session.delete(movie)
        db.session.commit()
        flash(msg_text, category='success')
    else:
        flash("Error occurred", category='error')
    return redirect(url_for('views.movies'))


@views.route('/movieWatched/<movie_id>')
@login_required
def watchMovie(movie_id):
    movie = Movie.query.filter_by(id=movie_id).first()
    if movie:
        tempBool = movie.haveWatched
        movie.haveWatched = not tempBool
        db.session.commit()
        if (movie.haveWatched):
            flash('Movie Watched', category='success')
        else:
            flash('Movie Unwatched', category='error')
    else:
        flash("Error occurred", category='error')
    return redirect(url_for('views.movies'))


@views.route('/songs', methods=['POST', 'GET'])
@login_required
def songs():
    if request.method == 'POST':
        song_name = request.form.get('songNameInput')
        song_artist = request.form.get('songArtistInput')
        newSong = Song(name=song_name, artist=song_artist, whoAdded=current_user.username, haveListened=False)
        db.session.add(newSong)
        db.session.commit()
        return redirect(url_for('views.songs'))

    allSongs = Song.query.all()
    notListened = []

    for song in allSongs:
        if not song.haveListened:
            notListened.append(song)

    if len(notListened) > 0:
        randSong = random.choice(notListened)
        return render_template('songs.html', user=current_user, songs=allSongs, randomSong=randSong.name)
    else:
        return render_template('songs.html', user=current_user, songs=allSongs, randomSong="All Songs Listened To")



@views.route('/listenSong/<song_id>')
@login_required
def listenSong(song_id):
    song = Song.query.filter_by(id=song_id).first()
    if song:
        tempBool = song.haveListened
        song.haveListened = not tempBool
        db.session.commit()
        if (song.haveListened):
            flash('Song Listened To', category='success')
        else:
            flash('Song Unlistened To', category='error')
    else:
        flash("Error Occurred", category='error')
    return redirect(url_for('views.songs'))


@views.route('/songDelete/<song_id>')
@login_required
def songDelete(song_id):
    song = Song.query.filter_by(id=song_id).first()
    if song:
        msg_text = f"Successfully Deleted {song.name}"
        db.session.delete(song)
        db.session.commit()
        flash(msg_text, category='success')
    else:
        flash("Error occurred", category='error')
    return redirect(url_for('views.songs'))


@views.route('/settings')
@login_required
def settings():
    return render_template('settings.html', user=current_user)


@views.context_processor
@login_required
def datetime_context_processor():
    def daysSince(currDate):
        daysSinceVar = (datetime.now().replace(hour=0, minute=0, second=0, microsecond=0) - currDate.replace(tzinfo=None, hour=0, minute=0, second=0, microsecond=0)).days
        if daysSinceVar == 1:
            return 'Yesterday'
        elif daysSinceVar == 0:
            return 'Today'
        else:
            return f'{daysSinceVar} days ago'

    return dict(daysSince=daysSince)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {{ JSGlue.include() }}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link
            rel="stylesheet"
            href="https://cdn.datatables.net/1.11.4/css/dataTables.bootstrap4.min.css"
            crossorigin="anonymous"
    >


    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{{ url_for('static', filename="style.css") }}">

    <title>{% block title %}Home{% endblock %}</title>
</head>


<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggle-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="movies" href="/movies">Movies</a>
                <a class="nav-item nav-link" id="songs" href="/songs">Songs</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                {% endif %}
            </div>
        </div>
        {% if user.is_authenticated %}

        {% endif %}
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                {% else %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-dismiss="alert">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}

    <div class="container">
        {% block pageBody %}
        {% endblock %}
    </div>

<!-- SCRIPTS BELOW -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
        src="https://code.jquery.com/jquery-3.5.1.js"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"
        crossorigin="anonymous"
    ></script>
    <script
        src="https://cdn.datatables.net/1.11.4/js/dataTables.bootstrap4.min.js"
        crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>

</body>
</html>

website/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block pageBody %}
    <br>
    <br>

    <h1 class="white text-center">Welcome to the new home page for the movie list site thing {{ user.username }}</h1>

    <br>
    <br>
    <br>

    <div id="homeImageCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#homeImageCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#homeImageCarousel" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{{ url_for('static', filename="assets/banner1.png") }}" alt="First Slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{{ url_for('static', filename="assets/banner2.png") }}" alt="Second Slide">
            </div>
        </div>
    <a class="carousel-control-prev" href="#homeImageCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#homeImageCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
    </div>

    <br>
    <br>
    <br>

    <div class="container-fluid white">
        <div class="jumbotron">
            <h1>Epic picturz</h1>
            <p>These are super epic pikchurs and stuff</p>
        </div>

    <div class="row gallery white">
        <div class="col-sm-6 col-md-4 col-lg-3">
            <img class="img-fluid" src="{{ url_for('static', filename="assets/pixelTony.png") }}">
            <p>This is an epic picture of tony from survivor!</p>
            <br>
            <img class="img-fluid" src="{{ url_for('static', filename="assets/fits.png") }}">
            <p>This silly cat thinks it can sit wherever!</p>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <img class="img-fluid" src="{{ url_for('static', filename="assets/wordleFunny.png") }}">
            <p>This is a gnarly picture of a funny word from a wordle guess!</p>
            <br>
            <img class="img-fluid" src="{{ url_for('static', filename="assets/four.png") }}">
            <p>Wowza, this guy is hot and i would totally have a poster of him in my room</p>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <img class="img-fluid" src="{{ url_for('static', filename="assets/up.jpg") }}">
            <p>This is a super dope picture of me "getting up" HAHAHAHHAHAHAHAHHAHAHAHAHA!</p>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3">
            <img class="img-fluid" src="{{ url_for('static', filename="assets/hotTom.jpg") }}">
            <p>This is super famous and hot actor Tom Holland in the movie Uncharted, man does he look silly!!</p>
        </div>
    </div>
    </div>

    <br>
    <br>
    <br>
    <br>
    <br>
    <br>


{#  Port Fairy ~ Australia  #}

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block pageBody %}
<form method="post">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="username">Username</label>
        <input type="username" class="form-control" id="username" name="username" placeholder="Enter username">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/movies.html
{% extends "base.html" %}
{% block title %}Movies{% endblock %}

{% block pageBody %}
    <br>
    <br>
    <br>

    <h1 align="center">Welcome to the movie list site thing, {{ user.username }}!</h1>

    <br>
    <br>
    <br>

    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#randomMovieModal">Random Movie</button>
    <div class="modal fade" id="randomMovieModal" tabindex="-1" role="dialog"
         aria-labelledby="randomMovieModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="randomMovieModalLabel">Random Movie Picker</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ randomMovie }}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#movieModal">Add Movie</button>
    <form method="post">
        <div class="modal fade" id="movieModal" tabindex="-1" role="dialog"
             aria-labelledby="movieModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="movieModalLabel">Add Movie</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post">
                            <div class="form-group">
                                <label for="movieNameInput">Name</label>
                                <input type="text" class="form-control" id="movieNameInput"
                                       name="movieNameInput" placeholder="Movie name">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <br>
    <br>

    <table id="movieTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <thead class="table-light">
        <th class="th-sm">Movie</th>
        <th class="th-sm">Added By</th>
        <th class="th-sm">Date Added</th>
        <th class="th-sm"></th>
        </thead>
        <tbody>
        {% for movie in movies %}
            {% if movie.haveWatched %}
                <tr class="table-success">
                    <td>{{ movie.name }}</td>
                    <td>{{ movie.whoAdded }}</td>
                    <td>{{ daysSince(movie.dateAdded) }}</td>
                    <td align="right">
                        <a href="{{ url_for('views.watchMovie', movie_id=movie.id) }}" title="Watch Movie">
                            <button type="button" class="btn btn-outline-success">&#10003;</button>
                        </a>
                        <a href="{{ url_for('views.movieDelete', movie_id=movie.id) }}"
                           onclick="return confirm('Are you sure you want to delete {{ movie.name }}?');"
                           title="Delete Movie" }}>
                            <button type="button" class="btn btn-outline-danger">&times;</button>
                        </a>
                    </td>
                    <td>{{ movie.haveWatched }}</td>
                    <td>{{ movie.dateAdded }}</td>
                </tr>
            {% else %}
                <tr class="table-secondary">
                    <td>{{ movie.name }}</td>
                    <td>{{ movie.whoAdded }}</td>
                    <td>{{ daysSince(movie.dateAdded) }}</td>
                    <td align="right">
                        <a href="{{ url_for('views.watchMovie', movie_id=movie.id) }}" title="Watch Movie">
                            <button type="button" class="btn btn-outline-success">&#10003;</button>
                        </a>
                        <a href="{{ url_for('views.movieDelete', movie_id=movie.id) }}"
                           onclick="return confirm('Are you sure you want to delete {{ movie.name }}?');"
                           title="Delete Movie" }}>
                            <button type="button" class="btn btn-outline-danger">&times;</button>
                        </a>
                    </td>
                    <td>{{ movie.haveWatched }}</td>
                    <td>{{ movie.dateAdded }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    <br>
    <br>
    <br>
{% endblock %}

website/templates/settings.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block pageBody %}
    <p>This part is a work in progress, not too sure what to put here yet...</p>
{% endblock %}

website/templates/songs.html
{% extends "base.html" %}
{% block title %}Movies{% endblock %}

{% block pageBody %}
    <br>
    <br>
    <br>

    <h1 align="center">Welcome to the movie list site thing, {{ user.username }}!</h1>

    <br>
    <br>
    <br>

    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#randomSongModal">Random Song</button>
    <div class="modal fade" id="randomSongModal" tabindex="-1" role="dialog"
         aria-labelledby="randomSongModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="randomSongModalLabel">Random Song Picker</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>{{ randomSong }}</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#songModal">Add Song</button>
    <form method="post">
        <div class="modal fade" id="songModal" tabindex="-1" role="dialog"
             aria-labelledby="songModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="songModalLabel">Add Song</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post">
                            <div class="form-group">
                                <label for="songNameInput">Name</label>
                                <input type="text" class="form-control" id="songNameInput"
                                       name="songNameInput" placeholder="Song name">
                                <br>
                                <label for="songArtistInput">Artist</label>
                                <input type="text" class="form-control" id="songArtistInput" name="songArtistInput" placeholder="Artist">
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <br>
    <br>

    <table id="songTable" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <thead class="table-light">
        <th class="th-sm">Song</th>
        <th class="th-sm">Artist</th>
        <th class="th-sm">Added By</th>
        <th class="th-sm">Date Added</th>
        <th class="th-sm"></th>
        </thead>
        <tbody>
        {% for song in songs %}
            {% if song.haveListened %}
                <tr class="table-success">
                    <td>{{ song.name }}</td>
                    <td>{{ song.artist }}</td>
                    <td>{{ song.whoAdded }}</td>
                    <td>{{ daysSince(song.dateAdded) }}</td>
                    <td align="right">
                        <a href="{{ url_for('views.listenSong', song_id=song.id) }}" title="Listen to Song">
                            <button type="button" class="btn btn-outline-success">&#10003;</button>
                        </a>
                        <a href="{{ url_for('views.songDelete', song_id=song.id) }}"
                           onclick="return confirm('Are you sure you want to delete {{ song.name }}?');"
                           title="Delete Song" }}>
                            <button type="button" class="btn btn-outline-danger">&times;</button>
                        </a>
                    </td>
                    <td>{{ song.haveListened }}</td>
                    <td>{{ song.dateAdded }}</td>
                </tr>
            {% else %}
                <tr class="table-secondary">
                    <td>{{ song.name }}</td>
                    <td>{{ song.artist }}</td>
                    <td>{{ song.whoAdded }}</td>
                    <td>{{ daysSince(song.dateAdded) }}</td>
                    <td align="right">
                        <a href="{{ url_for('views.listenSong', song_id=song.id) }}" title="Listen to Song">
                            <button type="button" class="btn btn-outline-success">&#10003;</button>
                        </a>
                        <a href="{{ url_for('views.songDelete', song_id=song.id) }}"
                           onclick="return confirm('Are you sure you want to delete {{ song.name }}?');"
                           title="Delete Song" }}>
                            <button type="button" class="btn btn-outline-danger">&times;</button>
                        </a>
                    </td>
                    <td>{{ song.haveListened }}</td>
                    <td>{{ song.dateAdded }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    <br>
    <br>
    <br>
{% endblock %}